language: java
jdk:
- oraclejdk8
script:
- test/run.sh
notifications:
  slack:
    secure: rVmHqHTIeMQeGEYAXA6spwM4Vo9whKOhG5FNaw1nYRfsDeSzgO1YYwjAsAXfqQIArAcIvJhjALv2iNrWz+dBNCyNXEhd0XhWlpkDy9kYJR7c79SvtotNEmG3qbarrScOfBKKlMmJYPtPa7JGdUdIVhVFOQg2CK7JBzlOTx12/M8=
