dtw-web-dc:
  build: .
  links:
    - db
  ports:
    - "8080:8080"
  volumes:
    - ~/.gradle:/root/.gradle
    - .:/app
  environment:
    - SPRING_PROFILES_ACTIVE=prod
    - DB_USER=root
  command: ./gradlew bootRun

db:
  image: "mysql:5.6"
  environment:
    - MYSQL_ROOT_PASSWORD=verysecret
    - MYSQL_DATABASE=dtw
