server:
  port: 8080

spring:
  application:
    name: testLatticeApp
  datasource:
    url: jdbc:hsqldb:file:data/hsql-file-db;sql.syntax_mys=true
    username: sa
    password: ""
  jpa.hibernate.ddl-auto: validate

ribbon:
  ServerListRefreshInterval: 1000

endpoints:
  health:
    sensitive: false
  restart:
    enabled: true
  shutdown:
    enabled: true
