server:
  port: 8080

#TODO: figure out why I need this here and in bootstrap.yml
spring:
  application:
    name: testLatticeApp
  datasource:
    url: jdbc:hsqldb:file:data/hsql-file-db
    username: sa
    password: ""
  jpa.hibernate.ddl-auto: validate

ribbon:
  ServerListRefreshInterval: 1000

endpoints:
  health:
    sensitive: false
  restart:
    enabled: true
  shutdown:
    enabled: true
