package org.skinny.drive_to_work;

import org.springframework.beans.factory.annotation.Autowired
import org.springframework.hateoas.EntityLinks
import org.springframework.hateoas.ExposesResourceFor
import org.springframework.hateoas.Resources
import org.springframework.http.HttpEntity
import org.springframework.http.HttpStatus
import org.springframework.http.MediaType
import org.springframework.http.ResponseEntity
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RestController;
import java.time.LocalDate

@RestController
@RequestMapping("/dtw/api/episodes")
@ExposesResourceFor(Episode::class)
class EpisodeController @Autowired constructor(val entityLinks: EntityLinks) {

    @RequestMapping(method = arrayOf(RequestMethod.GET), produces = arrayOf(MediaType.APPLICATION_JSON_VALUE))
    fun episodes(): HttpEntity<Resources<Episode>> {
        val resources = Resources<Episode>(episodes)
        resources.add(entityLinks.linkToCollectionResource(Episode::class.java))
        return ResponseEntity<Resources<Episode>>(resources, HttpStatus.OK)
    }

    companion object {
        val episodes = listOf(
                Episode(317, "Lessons Learned: Theros", LocalDate.of(2016, 3, 25),
                        "Mark examines the lessons he learned from designing Theros",
                        "http://media.wizards.com/2016/podcasts/magic/drivetowork317_lessonslearnedtheros.mp3"),
                Episode(316, "Design Space", LocalDate.of(2016, 3, 25),
                        "Mark talks about the design space reserved for cards within a particular mechanic",
                        "http://media.wizards.com/2016/podcasts/magic/drivetowork316_designspace.mp3"),
                Episode(315, "Collaboration", LocalDate.of(2016, 3, 18),
                        "Mark talks about team dynamics and how to teams work together",
                        "http://media.wizards.com/2016/podcasts/magic/drivetowork315_collaboration.mp3"),
                Episode(314, "Getting a Job", LocalDate.of(2016, 3, 18),
                        "Mark talks about how people can get a job in Magic R&D at Wizards",
                        "http://media.wizards.com/2016/podcasts/magic/drivetowork314_gettingajob.mp3"),
                Episode(313, "Limited Edition, Part 6", LocalDate.of(2016, 3, 11),
                        "Mark concludes his six-part series on the design of Limited Edition (Alpha), Limited Edition (Beta), and Unlimited Edition",
                        "http://media.wizards.com/2016/podcasts/magic/drivetowork313_limitededitionpart6.mp3"),
                Episode(312, "Limited Edition, Part 5", LocalDate.of(2016, 3, 11),
                        "Mark continues with part 5 of his six-part series on the design of Limited Edition (Alpha), Limited Edition (Beta), and Unlimited Edition",
                        "http://media.wizards.com/2016/podcasts/magic/drivetowork312_limitededitionpart5.mp3"),
                Episode(311, "Limited Edition, Part 4", LocalDate.of(2016, 3, 4),
                        "Mark continues with part 4 of his six-part series on the design of Limited Edition (Alpha), Limited Edition (Beta), and Unlimited Edition",
                        "http://media.wizards.com/2016/podcasts/magic/drivetowork311_limitededitionpart4.mp3"),
                Episode(310, "Traveling", LocalDate.of(2016, 3, 4),
                        "Mark talks about his experiences traveling for his job and shares a few tips as well",
                        "http://media.wizards.com/2016/podcasts/magic/drivetowork310_traveling.mp3"),
                Episode(309, "Limited Edition, Part 3", LocalDate.of(2016, 2, 26),
                        "Mark continues with part 3 of his six-part series on the design of Limited Edition (Alpha), Limited Edition (Beta), and Unlimited Edition",
                        "http://media.wizards.com/2016/podcasts/magic/drivetowork309_limitededitionpart3.mp3"),
                Episode(308, "Limited Edition, Part 2", LocalDate.of(2016, 2, 26),
                        "Mark continues with part 2 of his six-part series on the design of Limited Edition (Alpha), Limited Edition (Beta), and Unlimited Edition",
                        "http://media.wizards.com/2016/podcasts/magic/drivetowork308_limitededitionpart2.mp3"),
                Episode(307, "Limited Edition, Part 1", LocalDate.of(2016, 2, 19),
                        "Mark begins a new six-part series on the design of Limited Edition (Alpha), Limited Edition (Beta), and Unlimited Edition",
                        "http://media.wizards.com/2016/podcasts/magic/drivetowork307_limitededitionpart1.mp3"),
                Episode(306, "Chris Rush", LocalDate.of(2016, 2, 19),
                        "Mark remembers the life of Christopher Rush and shares stories about their interactions",
                        "http://media.wizards.com/2016/podcasts/magic/drivetowork306_chrisrush.mp3"),
                Episode(305, "Reprints", LocalDate.of(2016, 2, 12),
                        "Mark talks about how and when Research and Development decide to use reprints in a design",
                        "http://media.wizards.com/2016/podcasts/magic/drivetowork305_reprints.mp3"),
                Episode(304, "Firsts, Part 2", LocalDate.of(2016, 2, 12),
                        "Mark concludes his two-part discussion with Melissa DeTora on their Magic firsts",
                        "http://media.wizards.com/2016/podcasts/magic/drivetowork304_firstspart2.mp3"),
                Episode(303, "Firsts, Part 1", LocalDate.of(2016, 2, 5),
                        " Mark is joined by Melissa DeTora for a two-parter where they discuss their Magic firsts",
                        "http://media.wizards.com/2016/podcasts/magic/drivetowork303_firstspart1.mp3"),
                Episode(302, "Head-to-Head", LocalDate.of(2016, 2, 5),
                        "Mark discusses his why and how he runs his Top 16 bracket activity on Twitter",
                        "http://media.wizards.com/2016/podcasts/magic/drivetowork302_headtohead.mp3"),
                Episode(301, "Celebrity", LocalDate.of(2016, 1, 29),
                        "Mark shares stories of his interactions with celebrities and as a Magic celebrity",
                        "http://media.wizards.com/2016/podcasts/magic/drivetowork301_celebrity.mp3"),
                Episode(300, "2013", LocalDate.of(2016, 1, 29),
                        "Mark continues his 20 years in 20 podcasts with the year 2013",
                        "http://media.wizards.com/2016/podcasts/magic/drivetowork300_2013.mp3"),
                Episode(299, "Choices vs. Options", LocalDate.of(2016, 1, 22),
                        "Mark talks about the decisions that game designers set up for players to make",
                        "http://media.wizards.com/2016/podcasts/magic/drivetowork299_choicevsoption.mp3"),
                Episode(298, "Star Wars Trading Card Game", LocalDate.of(2016, 1, 22),
                        "Mark talks about working with Richard Garfield ont he Star Wars TCG",
                        "http://media.wizards.com/2016/podcasts/magic/drivetowork298_starwarstcg.mp3"),
                Episode(297, "Creature Types", LocalDate.of(2016, 1, 15),
                        "Mark talks about the design and creative work behind creature types",
                        "http://media.wizards.com/2016/podcasts/magic/drivetowork297_creaturetypes.mp3"),
                Episode(296, "Dream Job", LocalDate.of(2016, 1, 15),
                        "Mark defines what a dream job is and how you can get one",
                        "http://media.wizards.com/2016/podcasts/magic/drivetowork296_dreamjob.mp3"),
                Episode(295, "Chicken Rabbit Donkey", LocalDate.of(2016, 1, 8),
                        "Mark talks about the three times he had to dress up as an animal for work",
                        "http://media.wizards.com/2016/podcasts/magic/drivetowork295_chickenrabbitdonkey.mp3"),
                Episode(294, "Dragons of Tarkir, Part 6", LocalDate.of(2016, 1, 8),
                        "Mark concludes his six-part series on the design of Dragons of Tarkir",
                        "http://media.wizards.com/2016/podcasts/magic/drivetowork294_dragonsoftarkirpart6.mp3"),
                Episode(293, "Dragons of Tarkir, Part 5", LocalDate.of(2016, 1, 1),
                        "Mark continues with part 5 of his six-part series on the design of Dragons of Tarkir",
                        "http://media.wizards.com/2015/podcasts/magic/drivetowork293_dragonsoftarkirpart5.mp3"),
                Episode(292, "Dragons of Tarkir, Part 4", LocalDate.of(2016, 1, 1),
                        "Mark continues with part 4 of his six-part series on the design of Dragons of Tarkir",
                        "http://media.wizards.com/2015/podcasts/magic/drivetowork292_dragonsoftarkirpart4.mp3"),
                Episode(291, "Live Life Like a Gamer", LocalDate.of(2015, 12, 25),
                        "Mark talks about important life skills people learn from gaming",
                        "http://media.wizards.com/2015/podcasts/magic/drivetowork291_livelikeagamer.mp3"),
                Episode(290, "Dragons of Tarkir, Part 3", LocalDate.of(2015, 12, 25),
                        "Mark continues with part 3 of his six-part series on the design of Dragons of Tarkir",
                        "http://media.wizards.com/2015/podcasts/magic/drivetowork290_dragonsoftarkirpart3.mp3"),
                Episode(289, "Dragons of Tarkir, Part 2", LocalDate.of(2015, 12, 18),
                        "Mark continues with part 2 of his six-part series on the design of Dragons of Tarkir",
                        "http://media.wizards.com/2015/podcasts/magic/drivetowork289_dragonsoftarkirpart2.mp3"),
                Episode(288, "Dragons of Tarkir, Part 1", LocalDate.of(2015, 12, 18),
                        "Mark begins a six-part series on the design of Dragons of Tarkir",
                        "http://media.wizards.com/2015/podcasts/magic/drivetowork288_dragonsoftarkirpart1.mp3"),
                Episode(287, "New Players", LocalDate.of(2015, 12, 11),
                        "Mark talks about the things that will teach a new player easier",
                        "http://media.wizards.com/2015/podcasts/magic/drivetowork287_newplayers.mp3"),
                Episode(286, "Designing Limited", LocalDate.of(2015, 12, 11),
                        "Mark talks about the many things design has to care about while designing a set for limited",
                        "http://media.wizards.com/2015/podcasts/magic/drivetowork286_designinglimited.mp3"),
                Episode(285, "Lessons Learned: Gatecrash", LocalDate.of(2015, 12, 4),
                        "Mark looks back as the co-lead of Dark Ascension (with Mark Gottlieb) and shares what he learned from it",
                        "http://media.wizards.com/2015/podcasts/magic/drivetowork285_lessonslearnedgatecrash.mp3"),
                Episode(284, "10 Things Every Game Needs: Hook", LocalDate.of(2015, 12, 4),
                        "Mark continues with part 9 in his series on 10-things every game needs",
                        "http://media.wizards.com/2015/podcasts/magic/drivetowork284_10thingshook.mp3"),
                Episode(283, "20 Years Later", LocalDate.of(2015, 11, 25),
                        "Mark talks about the difference in Magic and Wizards from when he started to today, 20 years later",
                        "http://media.wizards.com/2015/podcasts/magic/drivetowork283_20years.mp3"),
                Episode(282, "Most Asked Questions", LocalDate.of(2015, 11, 25),
                        "Mark talks about the questions he gets asked the most and the answers he chooses to give",
                        "http://media.wizards.com/2015/podcasts/magic/drivetowork282_mostaskedquestions.mp3"),
                Episode(281, "Social Media", LocalDate.of(2015, 11, 20),
                        "Mark talks about how he connects through social media to Magic fans",
                        "http://media.wizards.com/2015/podcasts/magic/drivetowork281_socialmedia.mp3"),
                Episode(280, "Bad Cards Revisited", LocalDate.of(2015, 11, 20),
                        "Mark talks about the revisit to his original article about why so-called bad cards exist",
                        "http://media.wizards.com/2015/podcasts/magic/drivetowork280_badcardsrevisited.mp3"),
                Episode(279, "Bad Cards", LocalDate.of(2015, 11, 13),
                        "Mark bases this podcast on his article about why so-called bad cards exist",
                        "http://media.wizards.com/2015/podcasts/magic/drivetowork279_badcards.mp3"),
                Episode(278, "Fate Reforged, Part 5", LocalDate.of(2015, 11, 13),
                        "Mark concludes his 5-part series on the design of Fate Reforged",
                        "http://media.wizards.com/2015/podcasts/magic/drivetowork278_fatereforgedpart5.mp3"),
                Episode(277, "Fate Reforged, Part 4", LocalDate.of(2015, 11, 6),
                        "Mark continues with part 4 of his five-part series on the design of Fate Reforged",
                        "http://media.wizards.com/2015/podcasts/magic/drivetowork277_fatereforgedpart4.mp3"),
                Episode(276, "Primary, Secondary, Tertiary", LocalDate.of(2015, 11, 6),
                        "Mark talks about the system which explains which colors each evergreen creature keyword falls into",
                        "http://media.wizards.com/2015/podcasts/magic/drivetowork276_primarysecondarytertiary.mp3"),
                Episode(275, "Fate Reforged, Part 3", LocalDate.of(2015, 10, 30),
                        "Mark continues with part 3 of his five-part series on the design of Fate Reforged",
                        "http://media.wizards.com/2015/podcasts/magic/drivetowork275_fatereforgedpart3.mp3"),
                Episode(274, "Fate Reforged, Part 2", LocalDate.of(2015, 10, 30),
                        "Mark continues with part 2 of his five-part series on the design of Fate Reforged",
                        "http://media.wizards.com/2015/podcasts/magic/drivetowork274_fatereforgedpart2.mp3"),
                Episode(273, "Fate Reforged, Part 1", LocalDate.of(2015, 10, 23),
                        "Mark begins a five-part series on the design of Fate Reforged",
                        "http://media.wizards.com/2015/podcasts/magic/drivetowork273_fatereforgedpart1.mp3"),
                Episode(272, "ARC System", LocalDate.of(2015, 10, 23),
                        "Mark taks about an idea that Wizards tried to expand TCGs to a broader audience",
                        "http://media.wizards.com/2015/podcasts/magic/drivetowork272_arcsystem.mp3"),
                Episode(271, "Un-Rules Manager", LocalDate.of(2015, 10, 16),
                        "Mark talks about being the rules manager for silver-bordered Magic",
                        "http://media.wizards.com/2015/podcasts/magic/drivetowork271_unrulesmanager.mp3"),
                Episode(270, "10 Things Every Game Needs: Flavor", LocalDate.of(2015, 10, 16),
                        "Mark continues with part 8 in his series on 10-things every game needs. ",
                        "http://media.wizards.com/2015/podcasts/magic/drivetowork270_10thingsflavor.mp3"),
                Episode(269, "Breaking Rules", LocalDate.of(2015, 10, 9),
                        "Magic is a game that often breaks its own rules. Today's podcast talks about when, why, and how you should break the rules in game design",
                        "http://media.wizards.com/2015/podcasts/magic/drivetowork269_breakingrules.mp3"),
                Episode(268, "PAX 2015", LocalDate.of(2015, 10, 9),
                        "Wizards pulled out all the stops with Magic at the Penny Arcade Expo held in Seattle this past August. This podcast talks all about it, including the full tale of my crazy seventeen-hour day",
                        "http://media.wizards.com/2015/podcasts/magic/drivetowork268_pax2015.mp3")
        )
    }
}
